# Generated by Django 6.1.1 on 2026-09-29 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feeder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("feeder_type", models.CharField(max_length=60)),
                ("serves", models.CharField(max_length=120)),
                ("last_refilled", models.DateField()),
                ("refill_interval_days", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["zone__area", "name"],
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("coops", "Coops"),
                            ("pens", "Pens"),
                            ("enclosures", "Enclosures"),
                        ],
                        max_length=20,
                    ),
                ),
                ("kind", models.CharField(max_length=40)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("roam_x", models.FloatField(blank=True, null=True)),
                ("roam_y", models.FloatField(blank=True, null=True)),
                ("roam_width", models.FloatField(blank=True, null=True)),
                ("roam_height", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["area", "name"],
            },
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("chicken", "Chicken"),
                            ("cow", "Cow"),
                            ("pig", "Pig"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(unique=True)),
                ("tag_id", models.CharField(max_length=20, unique=True)),
                ("type_label", models.CharField(max_length=40)),
                (
                    "sex",
                    models.CharField(
                        choices=[("F", "Female"), ("M", "Male")], max_length=1
                    ),
                ),
                ("breed", models.CharField(max_length=60)),
                ("birth_date", models.DateField()),
                (
                    "fertility_status",
                    models.CharField(
                        choices=[
                            ("laying", "Laying"),
                            ("brooding", "Brooding"),
                            ("pregnant", "Pregnant (calving)"),
                            ("lactating", "Lactating / nursing"),
                            ("open", "Not calving"),
                            ("breeding_male", "Breeding male"),
                            ("immature", "Immature"),
                        ],
                        max_length=20,
                    ),
                ),
                ("egg_count_mtd", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("sick", "Sick"),
                            ("recovering", "Recovering"),
                        ],
                        default="healthy",
                        max_length=12,
                    ),
                ),
                (
                    "photo",
                    models.CharField(
                        blank=True,
                        help_text="Path under /animals/ in the frontend",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "dam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offspring",
                        to="farm.animal",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="animals",
                        to="farm.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["species", "name"],
            },
        ),
        migrations.CreateModel(
            name="FeederContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_name", models.CharField(max_length=120)),
                ("category", models.CharField(max_length=40)),
                ("capacity_lbs", models.DecimalField(decimal_places=1, max_digits=7)),
                ("current_lbs", models.DecimalField(decimal_places=1, max_digits=7)),
                (
                    "daily_usage_lbs",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "feeder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="farm.feeder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(max_length=120)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "peak_temp_rise_f",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_events",
                        to="farm.animal",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("vaccine", "Vaccination"),
                            ("medication", "Medication"),
                            ("supplement", "Supplement"),
                        ],
                        max_length=12,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("dose", models.CharField(blank=True, max_length=120)),
                ("route", models.CharField(blank=True, max_length=60)),
                (
                    "times",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated HH:MM dosing times",
                        max_length=60,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("withdrawal", models.CharField(blank=True, max_length=120)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="farm.animal",
                    ),
                ),
                (
                    "health_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatments",
                        to="farm.healthevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm_name", models.CharField(blank=True, max_length=120)),
                ("role", models.CharField(blank=True, max_length=60)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("farm_address", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feeder",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feeders",
                to="farm.zone",
            ),
        ),
        migrations.CreateModel(
            name="LocationPing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pings",
                        to="farm.animal",
                    ),
                ),
            ],
            options={
                "ordering": ["animal", "timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="farm_locati_timesta_a138a3_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TemperatureRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("temp_f", models.DecimalField(decimal_places=1, max_digits=5)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temperatures",
                        to="farm.animal",
                    ),
                ),
            ],
            options={
                "ordering": ["animal", "date"],
                "unique_together": {("animal", "date")},
            },
        ),
        migrations.CreateModel(
            name="WeightRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("weight_lbs", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weights",
                        to="farm.animal",
                    ),
                ),
            ],
            options={
                "ordering": ["animal", "date"],
                "unique_together": {("animal", "date")},
            },
        ),
    ]
