# Generated by Django 6.1.1 on 2026-09-29 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incubator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('capacity', models.PositiveIntegerField(default=12)),
                ('incubation_days', models.PositiveIntegerField(default=21)),
                ('lockdown_day', models.PositiveIntegerField(default=18)),
                ('temp_f', models.DecimalField(decimal_places=1, max_digits=4)),
                ('humidity_pct', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incubators', to='farm.zone')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IncubatorEgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveIntegerField()),
                ('laid_date', models.DateField()),
                ('set_date', models.DateField(help_text='Day the egg went into the incubator')),
                ('last_checked', models.DateField()),
                ('color', models.CharField(choices=[('white', 'White'), ('cream', 'Cream'), ('light_brown', 'Light brown'), ('brown', 'Brown'), ('dark_brown', 'Dark brown')], max_length=12)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra large'), ('jumbo', 'Jumbo')], max_length=12)),
                ('weight_g', models.DecimalField(decimal_places=1, max_digits=4)),
                ('shell', models.CharField(blank=True, max_length=80)),
                ('candling', models.CharField(choices=[('not_candled', 'Not yet candled'), ('developing', 'Developing'), ('unclear', 'Unclear, recheck'), ('clear', 'Clear (infertile)')], default='not_candled', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('hen', models.ForeignKey(limit_choices_to={'sex': 'F', 'species': 'chicken'}, on_delete=django.db.models.deletion.PROTECT, related_name='incubated_eggs', to='farm.animal')),
                ('incubator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eggs', to='farm.incubator')),
            ],
            options={
                'ordering': ['incubator', 'slot'],
                'unique_together': {('incubator', 'slot')},
            },
        ),
    ]
