# Generated by Django 6.1.1 on 2026-10-08 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def roles_to_choices(apps, schema_editor):
    """Role used to be free text (e.g. "Farm Owner"). Every existing account becomes a Student."""
    apps.get_model("farm", "UserProfile").objects.exclude(role__in=["student", "volunteer", "instructor"]).update(
        role="student"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0002_incubator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="office_hours",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="office_location",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                help_text="Instructor who added this volunteer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="volunteers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="volunteer",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(roles_to_choices, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("volunteer", "Volunteer"),
                    ("instructor", "Instructor"),
                ],
                default="student",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("section", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                ("term_start", models.DateField()),
                (
                    "term_end",
                    models.DateField(help_text="Semesters default to 16 weeks"),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses_taught",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True, related_name="courses", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-term_start", "name", "section"],
            },
        ),
        migrations.CreateModel(
            name="FarmUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("body", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        choices=[
                            ("refill_feeder", "Refill feeder"),
                            ("special_feeding", "Special feeding"),
                            ("medication", "Administer medication"),
                            ("vaccination", "Administer vaccination"),
                            ("weights", "Take weights"),
                            ("temperatures", "Take temperatures"),
                            ("routine_exam", "Routine examination"),
                            ("special_exam", "Special examination"),
                        ],
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField()),
                ("due_time", models.TimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=300)),
                (
                    "veterinarian",
                    models.CharField(
                        blank=True,
                        help_text="Summer vet who performs the task",
                        max_length=120,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("completion_note", models.CharField(blank=True, max_length=300)),
                (
                    "animal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="farm.animal",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feeder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="farm.feeder",
                    ),
                ),
                (
                    "treatment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="farm.treatment",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "due_time", "id"],
                "indexes": [
                    models.Index(
                        fields=["assignee", "due_date"],
                        name="farm_assign_assigne_986889_idx",
                    )
                ],
            },
        ),
    ]
