# Generated by Django 6.1.1 on 2026-10-10 00:26

import django.db.models.deletion
from django.db import migrations, models

# Layout from farm_data.ZONES at the time of this migration, so a farm seeded earlier gets the
# night shelters and the trimmed runs without a reseed.
ROAMS = {
    "Longbourn Coop": (50, 55, 160, 110),
    "Orchard Coop": (220, 55, 150, 110),
    "Frat House Coop": (50, 195, 150, 90),
    "Cloverfield Pasture": (55, 355, 225, 140),
    "Upper Enclosure": (445, 55, 415, 225),
    "Lower Enclosure": (445, 345, 415, 255),
}
SHELTERS = [
    ("Boar Shed", "boar-shed", "pens", (295, 365, 65, 45), "Cloverfield Pasture"),
    ("Upper Barn", "upper-barn", "enclosures", (875, 55, 75, 55), "Upper Enclosure"),
    ("Lower Barn", "lower-barn", "enclosures", (875, 345, 75, 55), "Lower Enclosure"),
]


def add_shelters(apps, schema_editor):
    Zone = apps.get_model("farm", "Zone")
    Animal = apps.get_model("farm", "Animal")
    if not Zone.objects.exists():
        return  # empty database: seed_farm builds the layout
    for name, (x, y, w, h) in ROAMS.items():
        Zone.objects.filter(name=name).update(roam_x=x, roam_y=y, roam_width=w, roam_height=h)
    for name, slug, area, (x, y, w, h), day_zone in SHELTERS:
        shelter, _ = Zone.objects.get_or_create(
            name=name, defaults=dict(slug=slug, area=area, kind="barn", x=x, y=y, width=w, height=h))
        Animal.objects.filter(zone__name=day_zone).update(night_zone=shelter)
    # The nursing sow sleeps with her piglets.
    Animal.objects.filter(offspring__zone__name="Cloverfield Farrowing Barn").distinct().update(
        night_zone=Zone.objects.filter(name="Cloverfield Farrowing Barn").first())


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0003_roles_classes_assignments"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="night_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="night_animals",
                to="farm.zone",
            ),
        ),
        migrations.RunPython(add_shelters, migrations.RunPython.noop),
    ]
